apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goat-exporter
  namespace: goat-node
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: goat-exporter.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goat-exporter
                port:
                  number: 80
